# Generated by Django 5.1.2 on 2024-10-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.PositiveSmallIntegerField()),
                ('age', models.PositiveSmallIntegerField()),
                ('address', models.PositiveSmallIntegerField()),
                ('famsize', models.PositiveSmallIntegerField()),
                ('Pstatus', models.PositiveSmallIntegerField()),
                ('Medu', models.PositiveSmallIntegerField()),
                ('Fedu', models.PositiveSmallIntegerField()),
                ('Mjob', models.PositiveSmallIntegerField()),
                ('Fjob', models.PositiveSmallIntegerField()),
                ('reason', models.PositiveSmallIntegerField()),
                ('guardian', models.PositiveSmallIntegerField()),
                ('traveltime', models.PositiveSmallIntegerField()),
                ('studytime', models.PositiveSmallIntegerField()),
                ('failures', models.PositiveSmallIntegerField()),
                ('schoolsup', models.PositiveSmallIntegerField()),
                ('famsup', models.PositiveSmallIntegerField()),
                ('paid', models.PositiveSmallIntegerField()),
                ('activities', models.PositiveSmallIntegerField()),
                ('nursery', models.PositiveSmallIntegerField()),
                ('higher', models.PositiveSmallIntegerField()),
                ('internet', models.PositiveSmallIntegerField()),
                ('romantic', models.PositiveSmallIntegerField()),
                ('famrel', models.PositiveSmallIntegerField()),
                ('freetime', models.PositiveSmallIntegerField()),
                ('goout', models.PositiveSmallIntegerField()),
                ('Dalc', models.PositiveSmallIntegerField()),
                ('Walc', models.PositiveSmallIntegerField()),
                ('health', models.PositiveSmallIntegerField()),
                ('absences', models.PositiveSmallIntegerField()),
                ('G1', models.PositiveSmallIntegerField(null=True)),
                ('G2', models.PositiveSmallIntegerField(null=True)),
                ('G3', models.PositiveSmallIntegerField(null=True)),
                ('G4', models.PositiveSmallIntegerField(null=True)),
                ('G5', models.PositiveSmallIntegerField(null=True)),
                ('G6', models.PositiveSmallIntegerField(null=True)),
                ('G7', models.PositiveSmallIntegerField(null=True)),
                ('Grade_8_Marks', models.PositiveSmallIntegerField()),
                ('Grade_9_Marks', models.PositiveSmallIntegerField()),
                ('Grade_10_Marks', models.PositiveSmallIntegerField()),
                ('Grade_11_Marks', models.PositiveSmallIntegerField()),
                ('Grade_12_Marks', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('semester', models.PositiveSmallIntegerField()),
                ('course', models.PositiveSmallIntegerField()),
                ('student_categories', models.CharField(max_length=50)),
                ('cluster_group', models.PositiveSmallIntegerField(default=3)),
            ],
        ),
    ]
