from django.db import models

# Create your models here.
class Students(models.Model):
    sex = models.PositiveSmallIntegerField(default = 0)
    age = models.PositiveSmallIntegerField(default = 0)
    address = models.PositiveSmallIntegerField(default = 0)
    famsize = models.PositiveSmallIntegerField(default = 0)
    Pstatus = models.PositiveSmallIntegerField(default = 0)
    Medu = models.PositiveSmallIntegerField(default = 0)
    Fedu = models.PositiveSmallIntegerField(default = 0)
    Mjob = models.PositiveSmallIntegerField(default = 0)
    Fjob = models.PositiveSmallIntegerField(default = 0)
    reason = models.PositiveSmallIntegerField(default = 0)
    guardian = models.PositiveSmallIntegerField(default = 0)
    traveltime = models.PositiveSmallIntegerField(default = 0)
    studytime = models.PositiveSmallIntegerField(default = 0)
    failures = models.PositiveSmallIntegerField(default = 0)
    schoolsup = models.PositiveSmallIntegerField(default = 0)
    famsup = models.PositiveSmallIntegerField(default = 0)
    paid = models.PositiveSmallIntegerField(default = 0)
    activities = models.PositiveSmallIntegerField(default = 0)
    nursery = models.PositiveSmallIntegerField(default = 0)
    higher = models.PositiveSmallIntegerField(default = 0)
    internet = models.PositiveSmallIntegerField(default = 0)
    romantic = models.PositiveSmallIntegerField(default = 0)
    famrel = models.PositiveSmallIntegerField(default = 0)
    freetime = models.PositiveSmallIntegerField(default = 0)
    goout = models.PositiveSmallIntegerField(default = 0)
    Dalc = models.PositiveSmallIntegerField(default = 0)
    Walc = models.PositiveSmallIntegerField(default = 0)
    health = models.PositiveSmallIntegerField(default = 0)
    absences = models.PositiveSmallIntegerField(default = 0)
    G1 = models.PositiveSmallIntegerField(default = 0,null = True, blank=True)
    G2 = models.PositiveSmallIntegerField(default = 0,null = True, blank=True)
    G3 = models.PositiveSmallIntegerField(default = 0,null = True, blank=True)
    G4 = models.PositiveSmallIntegerField(default = 0,null = True, blank=True)
    G5 = models.PositiveSmallIntegerField(default = 0,null = True, blank=True)
    G6 = models.PositiveSmallIntegerField(default = 0,null = True, blank=True)
    G7 = models.PositiveSmallIntegerField(default = 0,null = True, blank=True)
    Grade_8_Marks = models.PositiveSmallIntegerField(default = 0)
    Grade_9_Marks = models.PositiveSmallIntegerField(default = 0)
    Grade_10_Marks = models.PositiveSmallIntegerField(default = 0)
    Grade_11_Marks = models.PositiveSmallIntegerField(default = 0)
    Grade_12_Marks = models.PositiveSmallIntegerField(default = 0)
    name = models.CharField(max_length=50, default="Yash")
    semester = models.PositiveSmallIntegerField(default = 0)
    course = models.PositiveSmallIntegerField(default = 0)
    student_categories = models.CharField(default="weak",max_length=50,null = True, blank=True)
    cluster_group = models.PositiveSmallIntegerField(default=3,null = True, blank=True)

    def __str__(self):
        return self.name
    